### ISSUE TITLE
Error: Array values can't have mixed types

### ISSUE THREAD

**Issue by d9k** [egomobile/swagger-ui-cli#2]
Tried to use with https://github.com/apache/superset/blob/1.4.0rc2/docs/src/resources/openapi.json, fails with error:

```
> swagger-ui docs/src/resources/openapi.json                                           
🚨 Error: Array values can't have mixed types
    at arrayOneTypeError (/home/d9k/.nvm/versions/node/v14.16.1/lib/node_modules/swagger-ui-cli/node_modules/@iarna/toml/stringify.js:22:10)
    at validateArray (/home/d9k/.nvm/versions/node/v14.16.1/lib/node_modules/swagger-ui-cli/node_modules/@iarna/toml/stringify.js:234:11)
    at stringifyInlineArray (/home/d9k/.nvm/versions/node/v14.16.1/lib/node_modules/swagger-ui-cli/node_modules/@iarna/toml/stringify.js:241:16)
    at stringifyInline (/home/d9k/.nvm/versions/node/v14.16.1/lib/node_modules/swagger-ui-cli/node_modules/@iarna/toml/stringify.js:183:14)
    at /home/d9k/.nvm/versions/node/v14.16.1/lib/node_modules/swagger-ui-cli/node_modules/@iarna/toml/stringify.js:243:37
    at Array.map (<anonymous>)
    at stringifyInlineArray (/home/d9k/.nvm/versions/node/v14.16.1/lib/node_modules/swagger-ui-cli/node_modules/@iarna/toml/stringify.js:243:28)
    at stringifyInline (/home/d9k/.nvm/versions/node/v14.16.1/lib/node_modules/swagger-ui-cli/node_modules/@iarna/toml/stringify.js:183:14)
    at stringifyAnyInline (/home/d9k/.nvm/versions/node/v14.16.1/lib/node_modules/swagger-ui-cli/node_modules/@iarna/toml/stringify.js:161:10)
    at /home/d9k/.nvm/versions/node/v14.16.1/lib/node_modules/swagger-ui-cli/node_modules/@iarna/toml/stringify.js:55:62
```

Tried to convert from openapi 3 to swagger 2 format, same error:

```
> api-spec-converter --from openapi_3 --to swagger_2 docs/src/resources/openapi.json > swagger.json
> swagger-ui swagger.json                                                    
 🚨 Error: Array values can't have mixed types
    at arrayOneTypeError (/home/d9k/.nvm/versions/node/v14.16.1/lib/node_modules/swagger-ui-cli/node_modules/@iarna/toml/stringify.js:22:10)
    at validateArray (/home/d9k/.nvm/versions/node/v14.16.1/lib/node_modules/swagger-ui-cli/node_modules/@iarna/toml/stringify.js:234:11)
    at stringifyInlineArray (/home/d9k/.nvm/versions/node/v14.16.1/lib/node_modules/swagger-ui-cli/node_modules/@iarna/toml/stringify.js:241:16)
    at stringifyInline (/home/d9k/.nvm/versions/node/v14.16.1/lib/node_modules/swagger-ui-cli/node_modules/@iarna/toml/stringify.js:183:14)
    at /home/d9k/.nvm/versions/node/v14.16.1/lib/node_modules/swagger-ui-cli/node_modules/@iarna/toml/stringify.js:243:37
    at Array.map (<anonymous>)
    at stringifyInlineArray (/home/d9k/.nvm/versions/node/v14.16.1/lib/node_modules/swagger-ui-cli/node_modules/@iarna/toml/stringify.js:243:28)
    at stringifyInline (/home/d9k/.nvm/versions/node/v14.16.1/lib/node_modules/swagger-ui-cli/node_modules/@iarna/toml/stringify.js:183:14)
    at stringifyAnyInline (/home/d9k/.nvm/versions/node/v14.16.1/lib/node_modules/swagger-ui-cli/node_modules/@iarna/toml/stringify.js:161:10)
    at /home/d9k/.nvm/versions/node/v14.16.1/lib/node_modules/swagger-ui-cli/node_modules/@iarna/toml/stringify.js:55:62

```

**Comment by ghost** [comment]
@d9k 

New versions since `0.12.2` should have the following CLI flags

- `--no-json`
- `--no-toml`
- `--no-yaml`

to control, if you want to disable support for one of these formats.

In your case it could be something like:

```bash
swagger-ui docs/src/resources/openapi.json --no-toml
```
